services:
  dockpeek:
    container_name: dockpeek
    image: ghcr.io/dockpeek/dockpeek:latest
    environment:
      - SECRET_KEY=my_secret_key  
      - USERNAME=admin            
      - PASSWORD=admin   
      
      # Docker Host 1
      - DOCKER_HOST_1_URL=unix:///var/run/docker.sock
      - DOCKER_HOST_1_NAME=MyServer1                 
      - DOCKER_HOST_1_PUBLIC_HOSTNAME=   

      # Docker Host 2
      - DOCKER_HOST_2_URL=tcp://192.168.1.168:2375    
      - DOCKER_HOST_2_NAME=Synology                   
      - DOCKER_HOST_2_PUBLIC_HOSTNAME=NAS    
    ports:
      - "3420:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped